Github:
- any-glob-to-any-file: ['.github/**/*']

Images:
- any-glob-to-any-file: [static/images/**/*]

Architecture:
- any-glob-to-any-file: 
  - local/**/*
  - layouts/**/*
  - config/**/*
  - assets/**/*

$1:
- any-glob-to-any-file: ['content/en/([^/]+)/.*']

FAQ:
- any-glob-to-any-file: ['content/en/*/faq/*']

Guide: 
- any-glob-to-any-file: ['content/en/*/guide/*']
