extends: existence
message: "Avoid vague link text like '%s' (ignore this error if you have other descriptive words along with '%s')."
link: 'https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#links'
ignorecase: true
scope: link
level: error
tokens:
  - here
  - documentation
  - this
  - page
